In [6]:
from tensorflow.keras.preprocessing.text import one_hot

#### Sentences

In [7]:
sent=['the glass of mik',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [8]:
sent

['the glass of mik',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

##### Define the vocabulary size

###### One-hot representation

In [9]:
voc_size=10000

In [10]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3924, 6908, 6924, 5342],
 [3924, 6908, 6924, 4582],
 [3924, 6070, 6924, 733],
 [8634, 5933, 4067, 6487, 5687],
 [8634, 5933, 4067, 6487, 4087],
 [6809, 3924, 930, 6924, 8318],
 [9533, 2108, 7585, 6487]]

###### Word Embedding Representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3924 6908 6924 5342]
 [   0    0    0    0 3924 6908 6924 4582]
 [   0    0    0    0 3924 6070 6924  733]
 [   0    0    0 8634 5933 4067 6487 5687]
 [   0    0    0 8634 5933 4067 6487 4087]
 [   0    0    0 6809 3924  930 6924 8318]
 [   0    0    0    0 9533 2108 7585 6487]]


#### Feature Representation

In [14]:
dim=10

In [29]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_shape=(sent_length,)))
model.build()

In [30]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([[[ 0.0285976 ,  0.04631207, -0.00358213, -0.0376596 ,
         -0.04114353,  0.03049013,  0.02673307,  0.03592468,
          0.00895162,  0.04234786],
        [ 0.0285976 ,  0.04631207, -0.00358213, -0.0376596 ,
         -0.04114353,  0.03049013,  0.02673307,  0.03592468,
          0.00895162,  0.04234786],
        [ 0.0285976 ,  0.04631207, -0.00358213, -0.0376596 ,
         -0.04114353,  0.03049013,  0.02673307,  0.03592468,
          0.00895162,  0.04234786],
        [ 0.0285976 ,  0.04631207, -0.00358213, -0.0376596 ,
         -0.04114353,  0.03049013,  0.02673307,  0.03592468,
          0.00895162,  0.04234786],
        [-0.02006943, -0.00349691,  0.00442221, -0.03003154,
          0.02992251, -0.03030045, -0.03131988, -0.0471345 ,
          0.00884849, -0.04877849],
        [ 0.01752121,  0.02925109, -0.02762285,  0.03814505,
          0.03597647, -0.0364292 ,  0.04771555,  0.00339765,
          0.02951619,  0.00691339],
        [-0.02897176, -0.0300827 , -0.04947052,  0.0

In [25]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[[ 0.0494617 ,  0.03726963, -0.00629456,  0.04380733,
         -0.02562037, -0.01139917, -0.01726042,  0.02793333,
         -0.01439047, -0.02995409],
        [ 0.0494617 ,  0.03726963, -0.00629456,  0.04380733,
         -0.02562037, -0.01139917, -0.01726042,  0.02793333,
         -0.01439047, -0.02995409],
        [ 0.0494617 ,  0.03726963, -0.00629456,  0.04380733,
         -0.02562037, -0.01139917, -0.01726042,  0.02793333,
         -0.01439047, -0.02995409],
        [ 0.0494617 ,  0.03726963, -0.00629456,  0.04380733,
         -0.02562037, -0.01139917, -0.01726042,  0.02793333,
         -0.01439047, -0.02995409],
        [-0.00085939, -0.02729224, -0.0198691 , -0.01669455,
         -0.0146367 ,  0.0143206 , -0.03033089,  0.0459406 ,
         -0.00780817, -0.01599345],
        [-0.02456909,  0.0174212 , -0.01624648, -0.04767518,
          0.00155668,  0.02080565, -0.02892951, -0.04325992,
         -0.01605765, -0.0044387 ],
        [ 0.03969437,  0.03603978, -0.01629563, -0.0